pub mod technical;
pub mod fundamental;

use serde::{Deserialize, Serialize};

/// Market data snapshot for indicator evaluation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketData {
    pub symbol: String,
    pub timestamp: i64,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,
}

/// Signal generated by an indicator
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    pub symbol: String,
    pub indicator: String,
    pub signal_type: SignalType,
    pub strength: f64, // 0.0 to 1.0
    pub metadata: serde_json::Value,
    pub timestamp: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SignalType {
    Buy,
    Sell,
    Neutral,
}

/// Trait that all indicators must implement
pub trait Indicator: Send + Sync {
    /// Evaluate the indicator against market data
    fn evaluate(&self, data: &MarketData) -> Option<Signal>;
    
    /// Get the name of this indicator
    fn name(&self) -> &str;
    
    /// Get the category/family of this indicator
    fn category(&self) -> &str;
}
